dataset: "Isip"

path:
  corpus_path: "/data/tts/isip"
  lexicon_path: "lexicon/isip-lexicon.txt"
  raw_path: "/data/tts/isip/raw_data/isip"

preprocessing:
  val_size: 512
  text:
    text_cleaner: []
    language: "t1"
    max_length: 40
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0.0
    mel_fmax: 8000.0
  pitch:
    feature: "phoneme_level"
    normalization: true
  energy:
    feature: "phoneme_level"
    normalization: true